//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationStatu
    {
        public ConsultationStatu()
        {
            this.ManagementServices = new HashSet<ManagementService>();
            this.ServiceCategories = new HashSet<ServiceCategory>();
        }
    
        public string ConsultationId { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<ManagementService> ManagementServices { get; set; }
        public virtual ICollection<ServiceCategory> ServiceCategories { get; set; }
    }
}
