//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationCategoryStatu
    {
        public ConsultationCategoryStatu()
        {
            this.ServiceCategories = new HashSet<ServiceCategory>();
        }
    
        public string Consult_CategoryId { get; set; }
        public string CategoryId { get; set; }
        public bool Status { get; set; }
    
        public virtual ConsultationCategory ConsultationCategory { get; set; }
        public virtual ICollection<ServiceCategory> ServiceCategories { get; set; }
    }
}
