//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryEstimate
    {
        public LaboratoryEstimate()
        {
            this.ServiceEstimates = new HashSet<ServiceEstimate>();
        }
    
        public string Id { get; set; }
        public string CategoryId { get; set; }
        public string WorkerId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual LaboratoryCategory LaboratoryCategory { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<ServiceEstimate> ServiceEstimates { get; set; }
    }
}
