//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalImagingCategory
    {
        public MedicalImagingCategory()
        {
            this.MedicalImagingEstimates = new HashSet<MedicalImagingEstimate>();
            this.MedicalImagingCategoryStatus = new HashSet<MedicalImagingCategoryStatu>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MedicalImagingEstimate> MedicalImagingEstimates { get; set; }
        public virtual ICollection<MedicalImagingCategoryStatu> MedicalImagingCategoryStatus { get; set; }
    }
}
