//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionCategory
    {
        public PrescriptionCategory()
        {
            this.PrescriptionCategoryStatus = new HashSet<PrescriptionCategoryStatu>();
            this.PrescriptionEstimates = new HashSet<PrescriptionEstimate>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PrescriptionCategoryStatu> PrescriptionCategoryStatus { get; set; }
        public virtual ICollection<PrescriptionEstimate> PrescriptionEstimates { get; set; }
    }
}
