//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public string ServiceId { get; set; }
        public string CategoryId { get; set; }
    
        public virtual ConsultationCategoryStatu ConsultationCategoryStatu { get; set; }
        public virtual ConsultationStatu ConsultationStatu { get; set; }
        public virtual LaboratoryCategoryStatu LaboratoryCategoryStatu { get; set; }
        public virtual LaboratoryStatu LaboratoryStatu { get; set; }
        public virtual MedicalImaging MedicalImaging { get; set; }
        public virtual MedicalImagingCategoryStatu MedicalImagingCategoryStatu { get; set; }
        public virtual MedicalImagingStatu MedicalImagingStatu { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual PrescriptionCategoryStatu PrescriptionCategoryStatu { get; set; }
        public virtual PrescriptionStatu PrescriptionStatu { get; set; }
        public virtual VariousDocument VariousDocument { get; set; }
        public virtual VariousDocumentCategoryStatu VariousDocumentCategoryStatu { get; set; }
        public virtual VariousDocumentStatu VariousDocumentStatu { get; set; }
    }
}
