//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariousDocumentCategory
    {
        public VariousDocumentCategory()
        {
            this.VariousDocumentCategoryStatus = new HashSet<VariousDocumentCategoryStatu>();
            this.VariousDocumentEstimantes = new HashSet<VariousDocumentEstimante>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VariousDocumentCategoryStatu> VariousDocumentCategoryStatus { get; set; }
        public virtual ICollection<VariousDocumentEstimante> VariousDocumentEstimantes { get; set; }
    }
}
