//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitService
    {
        public string VisitId { get; set; }
        public string ServiceId { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Laboratory Laboratory { get; set; }
        public virtual MedicalImaging MedicalImaging { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual VariousDocument VariousDocument { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
