//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Accounts = new HashSet<Account>();
            this.Consultations = new HashSet<Consultation>();
            this.ConsultationEstimates = new HashSet<ConsultationEstimate>();
            this.Datings = new HashSet<Dating>();
            this.Laboratories = new HashSet<Laboratory>();
            this.LaboratoryEstimates = new HashSet<LaboratoryEstimate>();
            this.MedicalImagings = new HashSet<MedicalImaging>();
            this.MedicalImagingEstimates = new HashSet<MedicalImagingEstimate>();
            this.Prescriptions = new HashSet<Prescription>();
            this.PrescriptionEstimates = new HashSet<PrescriptionEstimate>();
            this.VariousDocuments = new HashSet<VariousDocument>();
            this.VariousDocumentEstimantes = new HashSet<VariousDocumentEstimante>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public short Age { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> SWD { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual ICollection<ConsultationEstimate> ConsultationEstimates { get; set; }
        public virtual ICollection<Dating> Datings { get; set; }
        public virtual ICollection<Laboratory> Laboratories { get; set; }
        public virtual ICollection<LaboratoryEstimate> LaboratoryEstimates { get; set; }
        public virtual ICollection<MedicalImaging> MedicalImagings { get; set; }
        public virtual ICollection<MedicalImagingEstimate> MedicalImagingEstimates { get; set; }
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        public virtual ICollection<PrescriptionEstimate> PrescriptionEstimates { get; set; }
        public virtual ICollection<VariousDocument> VariousDocuments { get; set; }
        public virtual ICollection<VariousDocumentEstimante> VariousDocumentEstimantes { get; set; }
    }
}
